# Generated by Django 6.0.7 on 2026-07-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin_emails',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('challenge_id', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('user_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='evaluated', max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(default='participant', max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
