import type { FileManifestEntry } from "@/types";

export const fileManifest: FileManifestEntry[] = [
  {
    id: "globals-css",
    path: "src/app/globals.css",
    category: "Theme",
    reason: "Defines the dark cyberpunk theme, neon green accents, and global styles matching the design mockup.",
    description: "Global CSS variables and utility classes for the Prompt War visual identity.",
  },
  {
    id: "root-layout",
    path: "src/app/layout.tsx",
    category: "Layout",
    reason: "Root layout wraps the app with fonts, auth provider, and toast notifications.",
    description: "Application shell with Geist fonts and global providers.",
  },
  {
    id: "landing-page",
    path: "src/app/page.tsx",
    category: "Pages",
    reason: "Public landing page with hero, CTAs, and neon mask visual from the design.",
    description: "Marketing homepage for Prompt War.",
  },
  {
    id: "login-page",
    path: "src/app/login/page.tsx",
    category: "Pages",
    reason: "Authentication entry point connected to the FastAPI JWT login endpoint.",
    description: "Login form with email, password, and register link.",
  },
  {
    id: "register-page",
    path: "src/app/register/page.tsx",
    category: "Pages",
    reason: "Participant registration form for hackathon sign-up.",
    description: "Registration with name, college, department, email, and password.",
  },
  {
    id: "dashboard-page",
    path: "src/app/(protected)/dashboard/page.tsx",
    category: "Pages",
    reason: "Main participant hub showing preparation countdown and quick access cards.",
    description: "Dashboard with timer and navigation shortcuts.",
  },
  {
    id: "resources-page",
    path: "src/app/(protected)/resources/page.tsx",
    category: "Pages",
    reason: "Displays admin-uploaded study materials with filter support.",
    description: "Resources list with empty state placeholder.",
  },
  {
    id: "challenge-page",
    path: "src/app/(protected)/challenge/page.tsx",
    category: "Pages",
    reason: "Core competition page with image, problem statement, Monaco editor, and submission.",
    description: "Challenge workspace for writing and submitting prompts.",
  },
  {
    id: "leaderboard-page",
    path: "src/app/(protected)/leaderboard/page.tsx",
    category: "Pages",
    reason: "Rankings table with highlighted current-user row.",
    description: "Participant leaderboard view.",
  },
  {
    id: "admin-dashboard",
    path: "src/app/admin/page.tsx",
    category: "Admin",
    reason: "Admin overview with stats, recent submissions, and quick actions.",
    description: "Admin control panel dashboard.",
  },
  {
    id: "admin-challenges",
    path: "src/app/admin/challenges/page.tsx",
    category: "Admin",
    reason: "Create/edit challenges, upload images, configure timers.",
    description: "Challenge management interface.",
  },
  {
    id: "admin-resources",
    path: "src/app/admin/resources/page.tsx",
    category: "Admin",
    reason: "Upload study materials (MD, JSON, PDF) for participants.",
    description: "Admin resource upload page.",
  },
  {
    id: "admin-submissions",
    path: "src/app/admin/submissions/page.tsx",
    category: "Admin",
    reason: "View all submitted prompts and evaluation status.",
    description: "Admin submissions review table.",
  },
  {
    id: "admin-participants",
    path: "src/app/admin/participants/page.tsx",
    category: "Admin",
    reason: "View registered participants from the backend.",
    description: "Participant registry table.",
  },
  {
    id: "admin-leaderboard",
    path: "src/app/admin/leaderboard/page.tsx",
    category: "Admin",
    reason: "Admin view of competition rankings.",
    description: "Admin leaderboard page.",
  },
  {
    id: "implementation-page",
    path: "src/app/implementation/page.tsx",
    category: "Meta",
    reason: "Explains architecture and requests permission for each generated file.",
    description: "Interactive implementation guide and file approval UI.",
  },
  {
    id: "protected-layout",
    path: "src/app/(protected)/layout.tsx",
    category: "Layout",
    reason: "Shared sidebar + navbar layout for authenticated participant pages.",
    description: "Participant app shell layout.",
  },
  {
    id: "admin-layout",
    path: "src/app/admin/layout.tsx",
    category: "Layout",
    reason: "Admin-specific sidebar with role protection (403 redirect).",
    description: "Admin app shell layout.",
  },
  {
    id: "api-client",
    path: "src/lib/api/client.ts",
    category: "API",
    reason: "Central Axios instance with JWT interceptors and 403 admin redirect.",
    description: "HTTP client configuration.",
  },
  {
    id: "api-auth",
    path: "src/lib/api/auth.ts",
    category: "API",
    reason: "Login, register, logout, and profile endpoints.",
    description: "Authentication API module.",
  },
  {
    id: "api-resources",
    path: "src/lib/api/resources.ts",
    category: "API",
    reason: "Fetch and download study materials.",
    description: "Resources API module.",
  },
  {
    id: "api-challenge",
    path: "src/lib/api/challenge.ts",
    category: "API",
    reason: "Fetch active challenge and timer configuration.",
    description: "Challenge API module.",
  },
  {
    id: "api-submissions",
    path: "src/lib/api/submissions.ts",
    category: "API",
    reason: "Submit prompts and fetch user submissions.",
    description: "Submissions API module.",
  },
  {
    id: "api-leaderboard",
    path: "src/lib/api/leaderboard.ts",
    category: "API",
    reason: "Fetch rankings and current user rank.",
    description: "Leaderboard API module.",
  },
  {
    id: "api-admin",
    path: "src/lib/api/admin.ts",
    category: "API",
    reason: "Admin stats, uploads, challenge creation, and participant management.",
    description: "Admin API module with multipart upload support.",
  },
  {
    id: "auth-context",
    path: "src/lib/auth/auth-context.tsx",
    category: "Auth",
    reason: "Global auth state, timer state, and login/logout handlers.",
    description: "React context for authentication flow.",
  },
  {
    id: "types",
    path: "src/types/index.ts",
    category: "Types",
    reason: "Shared TypeScript interfaces for frontend-backend contract.",
    description: "Domain type definitions.",
  },
  {
    id: "navbar",
    path: "src/components/layout/Navbar.tsx",
    category: "Components",
    reason: "Top bar with welcome message, notifications, and profile avatar.",
    description: "Authenticated and public navigation bars.",
  },
  {
    id: "sidebar",
    path: "src/components/layout/Sidebar.tsx",
    category: "Components",
    reason: "Persistent navigation with locked Challenge state and mobile menu.",
    description: "Sidebar navigation component.",
  },
  {
    id: "countdown-timer",
    path: "src/components/CountdownTimer.tsx",
    category: "Components",
    reason: "Reusable HH:MM:SS timer for preparation and submission phases.",
    description: "Countdown display component.",
  },
  {
    id: "prompt-editor",
    path: "src/components/PromptEditor.tsx",
    category: "Components",
    reason: "Monaco editor with character and token count for prompt submission.",
    description: "Prompt input editor component.",
  },
  {
    id: "leaderboard-table",
    path: "src/components/LeaderboardTable.tsx",
    category: "Components",
    reason: "Styled data table with highlighted current-user row.",
    description: "Leaderboard table component.",
  },
  {
    id: "upload-dialog",
    path: "src/components/UploadDialog.tsx",
    category: "Components",
    reason: "Reusable file upload modal for admin image and resource uploads.",
    description: "Upload dialog with drag-and-click interface.",
  },
  {
    id: "confirmation-modal",
    path: "src/components/ConfirmationModal.tsx",
    category: "Components",
    reason: "Success modal after prompt submission.",
    description: "Confirmation dialog with checkmark.",
  },
  {
    id: "backend-structure",
    path: "backend/README.md",
    category: "Backend",
    reason: "Documents planned FastAPI folder structure for future integration.",
    description: "Backend architecture placeholder.",
  },
];

export const implementationSteps = [
  {
    step: 1,
    title: "Project Scaffold",
    description:
      "Next.js App Router project with TypeScript, Tailwind CSS, and core dependencies.",
  },
  {
    step: 2,
    title: "Design System",
    description:
      "Dark theme with neon green accents, shadcn/ui primitives, and reusable layout components.",
  },
  {
    step: 3,
    title: "API Layer",
    description:
      "Centralized Axios client with JWT auth interceptors and typed endpoint modules.",
  },
  {
    step: 4,
    title: "Participant Flow",
    description:
      "Dashboard, Resources, Challenge (locked/unlocked), Leaderboard with role-aware routing.",
  },
  {
    step: 5,
    title: "Admin Flow",
    description:
      "Hidden admin routes protected by backend role check with 403 redirect to dashboard.",
  },
  {
    step: 6,
    title: "Backend Integration",
    description:
      "Connect to FastAPI at NEXT_PUBLIC_API_URL when backend is deployed.",
  },
];
